# SQLAlchemy models for Supabase

# Example stub for MonitoredChat
# from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
# from sqlalchemy.orm import declarative_base
# Base = declarative_base()

# class MonitoredChat(Base):
#     __tablename__ = "monitored_chats"
#     id = ...
#     user_id = ...
#     chat_id = ...
#     prompt = ...
#     last_processed_message_id = ...
#     is_active = ...

# TODO: Implement full SQLAlchemy model